import "./globals.css";

import { DM_Sans, Fraunces } from "next/font/google";

import type { Metadata } from "next";

const serifFont = Fraunces({
  variable: "--font-fraunces",
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
});

const sansFont = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BreakpointIndicator = function() { // REMOVE
  return (
    <div className="fixed bottom-4 right-4 z-50 flex items-center justify-center rounded-full bg-black px-3 py-2 text-xs font-mono text-white">
      <div className="block sm:hidden">xs</div>
      <div className="hidden sm:block md:hidden">sm</div>
      <div className="hidden md:block lg:hidden">md</div>
      <div className="hidden lg:block xl:hidden">lg</div>
      <div className="hidden xl:block 2xl:hidden">xl</div>
      <div className="hidden 2xl:block">2xl</div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${serifFont.variable} ${sansFont.variable} antialiased`}
      >
        {children}
        <BreakpointIndicator />
      </body>
    </html>
  );
}
