import "./globals.css";

import { DM_Sans, Fraunces } from "next/font/google";

import type { Metadata } from "next";

const playfairDisplay = Fraunces({
  variable: "--font-fraunces",
  weight: ['400', '600']
});

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfairDisplay.variable} ${dmSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
